#!/usr/bin/env bash

# This script creates a buildx environment if it doesn't exist,
# then builds and pushes a Docker image to a specified registry.

# Configuration
[[ -n "$1" ]] &&  { image_tag="${1}"; }
BUILDX_ENV_NAME="buildx"
REPOSITORY="sysopsro/awshelpers"

set -x
# Build and push the Docker image to the registry
build_and_push_image() {
    if [[ -z "${1}" ]]; then
        echo -n "Enter the image tag as awscli version (e.g., '2.22.6'): "
        read -r image_tag
    fi
    docker build \
        -t "${REPOSITORY}:${image_tag}" \
        --platform linux/amd64 \
        --push . || {
        echo "Failed to build and push Docker image."
        exit 1
    }
}

# Main script execution
build_and_push_image "${image_tag}"